### ISSUE TITLE
Broken browser caching?

### ISSUE THREAD

**Issue by mgedmin** [lepture/python-livereload#101]
I used livereload 2.3.2 on my Sphinx documentation successfully.  Then I pip installed git master.  Now reloading doesn't work:

1. I load a page in the browser, http://localhost:5500/foo.html
2. I edit foo.rst
3. I see the browser page reload
4. I still see the old content
5. I verify that the HTML file on disk has new content
6. I hit Ctrl-R to reload the browser tab manually
7. I still see the old content

I used Chromium's developer tools to look at the HTTP requests: livereload is responding with a 304 Not Modified to the request, which includes If-Modified-Since and If-None-Match headers.

I can see the new content if I use Ctrl+Shift+R to reload.  I see HTTP responses with Server: TornadoServer/4.0.2 and Etag: "586cf5820eb5f1633c93a490820935b6" which doesn't change, even when the HTML file changes.

**Comment by mgedmin** [comment]
Downgrading back to livereload 2.3.2 fixes this.

**Comment by mgedmin** [comment]
I see you've replaced your own StaticHandler with tornado.web.StaticHandler.

Bug in Tornado?

**Comment by mgedmin** [comment]
Seems to be https://github.com/tornadoweb/tornado/issues/892

**Comment by mgedmin** [comment]
BTW it appears that `debug=True` turns off Tornado's internal (badly broken) caching behavior.

**Comment by mgedmin** [comment]
Some related pull requests I haven't looked through yet:
- https://github.com/tornadoweb/tornado/pull/212
- https://github.com/tornadoweb/tornado/pull/299

I think they're solving a different problem: serving static files for an application, where you don't want some of the files to change in the middle of the app lifetime.

**Comment by lepture** [comment]
I've implemented a StaticHandler in livereload 2.3.2  and lower versions. The master is using tornado default StaticHandler now.

**Comment by RonnyPfannschmidt** [comment]
I implemented the use of the Tornado internal handler,

i suspect the main reason that its utterly broken caching eluded me is my setup for some reason caused the restart of the app-server in tornado to begin with

**Comment by lepture** [comment]
fixed in https://github.com/lepture/python-livereload/commit/7d0eb7e745c379a66158e6f05cfa7eeda56c0d44
