### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by d0ugal** [lepture/python-livereload#104]
We [have users](https://github.com/mkdocs/mkdocs/issues/473) that are hitting #79 - it appears to have been fixed in December. Are there plans to roll a release for python-livereload anytime soon?

Thanks!

**Comment by sloria** [comment]
+1. We are having issues related to https://github.com/lepture/python-livereload/issues/85 , which has been fixed on master. Would be great to see new release.

**Comment by d0ugal** [comment]
Better yet, let us know if we can do anything to help push a release forward.

**Comment by lepture** [comment]
@sloria @d0ugal  the master doesn't work on wsgi app now. I'll need to fix it.

**Comment by lepture** [comment]
here is the plan https://github.com/lepture/python-livereload/issues/105

**Comment by d0ugal** [comment]
Great, thanks!
