### ISSUE TITLE
version 2.4

### ISSUE THREAD

**Issue by lepture** [lepture/python-livereload#105]
A new release:

1. [x] wsgi app works
2. [x] bugfix https://github.com/lepture/python-livereload/issues/102
3. [x] clever watcher https://github.com/lepture/python-livereload/issues/98
4. [x] add a filter for directory watching https://github.com/lepture/python-livereload/issues/97
5. [x] unicode issue: https://github.com/lepture/python-livereload/pull/79
6. [x] watch without browser open: https://github.com/lepture/python-livereload/issues/109

**Comment by ionelmc** [comment]
You should consider making an easy release as whatever you have on PyPI (2.3.2) is broken on Windows.

**Comment by d0ugal** [comment]
@ionelmc not necessarily true, I'm aware of a number of users having success with livereload on windows. So it's probably a bug related to your setup, you should open an issue with more details.

**Comment by lepture** [comment]
2.4 will be released this week. There is only one task left.

**Comment by ionelmc** [comment]
@d0ugal The bin is broken on Windows. I can import the code (that's my current work-around).

**Comment by d0ugal** [comment]
@ionelmc I see, interesting. Our users all use it via us as a library, so we don't have that problem. It would be good if you could test master to see if it solves it for you still.

@lepture Great, I'd be happy to help do manual testing of the release before or when you roll one out if that would be useful.

**Comment by lepture** [comment]
@d0ugal that would be very helpful. I would manual test on Mac.

**Comment by d0ugal** [comment]
@lepture Should I do it now or wait for the final task to be completed? I can test Linux at least and I have a Windows VM that I can use for a quick test.

**Comment by lepture** [comment]
@d0ugal It would be better if you can find bugs as early as possible.

**Comment by d0ugal** [comment]
We just had [user run into this traceback with the dev version](https://github.com/mkdocs/mkdocs/issues/518#issuecomment-102055217) when trying to work around a bug that I think you have otherwise fixed in master.

    Serving on http://127.0.0.1:8000
    ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0', 'Accept-Language': 'en-US,en;q=0.5', 'X-Clickoncesupport': '( .NET CLR 3.5.30729; .NET4.0E)', 'Host': '127.0.0.1:8000', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "C:\tools\python\lib\site-packages\tornado\web.py", line 1348, in _execute
        result = yield result
      File "C:\tools\python\lib\site-packages\tornado\gen.py", line 807, in run
        value = future.result()
      File "C:\tools\python\lib\site-packages\tornado\concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\tools\python\lib\site-packages\tornado\gen.py", line 212, in wrapper
        yielded = next(result)
      File "C:\tools\python\lib\site-packages\tornado\web.py", line 2189, in get
        yield self.flush()
      File "C:\tools\python\lib\site-packages\tornado\web.py", line 832, in flush
        self._status_code, self._headers, chunk, include_footers)
      File "C:\tools\python\lib\site-packages\livereload\server.py", line 89, in transform_first_chunk
        chunk = chunk.replace(HEAD_END, self.script + HEAD_END)
    TypeError: Can't convert 'bytes' object to str implicitly
    ERROR:tornado.general:Cannot send error response after headers written

**Comment by lepture** [comment]
It is ready now. Need a final testing.

**Comment by d0ugal** [comment]
Was the change to the output logging format intentional?

**Comment by lepture** [comment]
@d0ugal the logging need to be fixed.

**Comment by lepture** [comment]
@d0ugal the colour logging is available now.

**Comment by d0ugal** [comment]
There are a few print statements in 'server.py' - could we use logging.info instead?

**Comment by lepture** [comment]
@d0ugal @bwmarrin It would be released soon. Could you help me to make a test?

**Comment by d0ugal** [comment]
Sure! What sorta test? Manual?

**Comment by lepture** [comment]
@d0ugal The watcher part has test cases. The server part doesn't. I have no idea on writing tests for the server part.

**Comment by bwmarrin** [comment]
@lepture What do you want me to test?

**Comment by lepture** [comment]
@bwmarrin oh, I mean to test it on windows.

**Comment by bwmarrin** [comment]
Will do, might be tomorrow though.  I've tested the master from just recently and things were working so I'll bet it still works :).  I'll let you know.

**Comment by d0ugal** [comment]
I've had a bit of a look into testing, but I'm not really sure. I'm not familiar enough with Tornado. I can try to look more when I have some spare time.

**Comment by lepture** [comment]
@d0ugal the server part is much difficult to test, it is a hybrid of http and websocket. It is really a tough work.

**Comment by lepture** [comment]
@bwmarrin any news? If it works well on windows, I'll release the 2.4 version.

**Comment by d0ugal** [comment]
@lepture My best suggestion is to move out as much logic as possible and then just accept that some bits can't be tested but that isn't ideal.

**Comment by bwmarrin** [comment]
Okay, so I've installed mkdocs normally, and the "master" branch of livereload. (Which displayed livereload-2.4)  Let me know if I should be using a different branch.

I'm not getting any unicode or other errors with mkdocs serve, everything looks okay.  If I edit a page than it updates as you would expect.  

If there's something specific you want me to check for, let me know.  Otherwise, it looks okay on Windows 7 / Python 3.4

**Comment by tkirill** [comment]
FYI this release fixes an issue with non-ascii characters on Windows in commit lepture/python-livereload@1c67c02 (PR #83).  It [affects](https://github.com/mkdocs/mkdocs/issues/352#issuecomment-106301525) `mkdocs serve` for example.

**Comment by tkirill** [comment]
One more vote for the new release.  In addition to the problem with [assets](https://github.com/mkdocs/mkdocs/issues/518#issuecomment-101347100) `mkdocs serve` can't display non-ascii symbols [even in a text](https://github.com/mkdocs/mkdocs/issues/352#issuecomment-106301525) because of the problems with encoding solved in this release in #83.  This makes live reload in Mkdocs unusable for users with non-ASCII alphabet.

**Comment by lepture** [comment]
Hi, everyone. 2.4 is there now.

**Comment by d0ugal** [comment]
@lepture Awesome. Thanks very much for all your effort with this release and the help you have given in particular to MkDocs users!
