### ISSUE TITLE
Don't try to browse fragments as whole URLs

### ISSUE THREAD

**Issue by vmalloc** [lepture/python-livereload#108]
When trying livereload with a page written in, say, Ember.JS, the reload causes the browser to try and browse to http://localhost:8000/#/some/path as if it were a whole URL, and does not properly distinguish the fragment from the URL...

**Comment by lepture** [comment]
Can you describe in this way:

1. what you are doing?
2. what do you expect?
3. what it really happens?

**Comment by vmalloc** [comment]
Turns out it was a bug on my end. Forgot to close the issue. Thanks!
