### ISSUE TITLE
RPM Packaging

### ISSUE THREAD

**Issue by williamjmorenor** [lepture/python-livereload#112]
Hi

https://bugzilla.redhat.com/show_bug.cgi?id=1230968#c2

I am packaging livereload in Fedora and want to ask you about a manpage for live releoad and if you can add a copyright header to the listed files. 

I will try to help with this, but I need to make some time for this first.

Regards

**Comment by d0ugal** [comment]
So, just to be clear, is the requirement to have the [LICENSE](https://github.com/lepture/python-livereload/blob/master/LICENSE) file duplicated at the top of all these files?

    livereload-2.4.0/%{py3dir}/livereload/__init__.py
    livereload-2.4.0/%{py3dir}/livereload/cli.py
    livereload-2.4.0/%{py3dir}/livereload/handlers.py
    livereload-2.4.0/%{py3dir}/livereload/server.py
    livereload-2.4.0/%{py3dir}/livereload/vendors/livereload.js
    livereload-2.4.0/%{py3dir}/livereload/watcher.py
    livereload-2.4.0/%{py3dir}/setup.py
    livereload-2.4.0/livereload/__init__.py
    livereload-2.4.0/livereload/cli.py
    livereload-2.4.0/livereload/handlers.py
    livereload-2.4.0/livereload/server.py
    livereload-2.4.0/livereload/vendors/livereload.js
    livereload-2.4.0/livereload/watcher.py
    livereload-2.4.0/setup.py

**Comment by d0ugal** [comment]
And what are the requirements for a manpage?

**Comment by williamjmorenor** [comment]
Here is a example:

http://www.gnu.org/licenses/gpl-howto.html

Can be somethink like this:

# Copyright 1998, 1999 Terry Jones

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:

#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#      with the distribution.
#   * Neither the name of the author nor the names of its contributors
#     may be used to endorse or promote products derived from this
#     software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

I am not sure about how to add coments to .js

The docs directory is a sphinx project? I can make the manpage with "make man" if you incluce docs in the pypi tarball. also I can build the documentation in html and include it in a subpackage python-livereload-docs

**Comment by d0ugal** [comment]
We don't need an example of a license file, @lepture has already chosen one, I linked it in my comment. It is here. https://github.com/lepture/python-livereload/blob/master/LICENSE

The requirement is to add that to the top of each file? why? Do you have any further reading on this that you can link me too?

You are correct, the documentation is a Sphinx project.

**Comment by lepture** [comment]
Why do I have to add the license content to the top of each file? Isn't that boring?

Ok. I've add a license field in the docstring: https://github.com/lepture/python-livereload/commit/fe610291e54943c9d12ecc56a58838bb4648f7a5 Would this be enough?

**Comment by lepture** [comment]
Close it now.
