### ISSUE TITLE
FakeWaiter: trigger tasks always

### ISSUE THREAD

**Issue by blueyed** [lepture/python-livereload#115]
I am using python-livereload for a `make watch` task, and would like to trigger
the `make scss` task always, without some browser having connected before.

This can be done by attaching some fake-Waiter like this:

    class FakeWaiter:
        "A no-op waiter to trigger scss re-building always."
        def write_message(*args, **kwargs):
            pass

    LiveReloadHandler.waiters.add(FakeWaiter)

I think this should be supported by default (by some option), or a `Waiter`
like this should be provided by python-livereload (in case the implementation
changes).

**Comment by lepture** [comment]
@blueyed https://github.com/lepture/python-livereload/commit/289d1131430e65206df8f46c040bb1668a277fed

**Comment by lepture** [comment]
upgrade to 2.4 https://github.com/lepture/python-livereload/blob/master/CHANGES.rst#version-240

**Comment by blueyed** [comment]
I've used master to test this.

This is my script:

    #!/usr/bin/env python
    from __future__ import print_function, absolute_import

    import fnmatch
    import os
    import sys

    from livereload import Server
    from livereload.watcher import INotifyWatcher
    from livereload.handlers import LiveReloadHandler


    def recursive_glob(rootdir='.', pattern='*'):
        return [os.path.join(walkdir, filename)
                for walkdir, _, filenames in os.walk(rootdir)
                for filename in filenames
                if fnmatch.fnmatch(filename, pattern)]

    try:
        watcher = INotifyWatcher()
    except Exception:
        watcher = None

    if len(sys.argv) > 1 and sys.argv[1] == 'livereload_only':
        # livereload only
        port = 35729
        application = None
        debug = False
    else:
        port = 8000
        from config.wsgi import application
        debug = True

    server = Server(application, watcher)

    for filepath in recursive_glob("socialee/static", "*.scss"):
        assert os.path.exists(filepath)
        print("Watching: %s" % filepath)
        # server.watch(filepath, 'make scss')
        # delay=forever: do not trigger livereload; done via css watches.
        # Ref: https://github.com/lepture/python-livereload/issues/63#issuecomment-60712396  # noqa
        server.watch(filepath, 'make scss', delay='forever')

    # Watch .css:
    for filepath in recursive_glob("socialee/static", "*.css"):
        assert os.path.exists(filepath)
        print("Watching: %s" % filepath)
        server.watch(filepath)

    for filepath in recursive_glob("socialee/templates", "*.html"):
        assert os.path.exists(filepath)
        print("Watching: %s" % filepath)
        server.watch(filepath)


    while True:
        try:
            # debug=False to prevent tornado from epolling for changed files to the
            # livereload app (does not use inotify).
            server.serve(port=port, debug=debug)
        except SyntaxError as e:
            print('ERROR_NOT_HAPPENING?: %s. Restarting.' % str(e))
            continue
        break

**Comment by lepture** [comment]
@blueyed you don't need to import `INotifyWatcher` yourself now. It will use INotifyWatcher if possible.

You can test on the example, remove the `open_url_delay` parameter.

**Comment by blueyed** [comment]
> you don't need to import INotifyWatcher yourself now. It will use INotifyWatcher if possible.

But is that relevant for this issue?

> You can test on the example, remove the `open_url_delay` parameter.

Do you mean the `delay` arg with `server.watch`?

**Comment by lepture** [comment]
@blueyed The example works well. You don't need to open a browser, it will watch and build when server started.

> You can test on the example, remove the open_url_delay parameter.

I mean `server.serve()`, so that it will not open a browser by default.

**Comment by blueyed** [comment]
@lepture 
> The example works well

Are you referring to my example? (it does not work for me)

>> remove the open_url_delay parameter
> I mean server.serve(), so that it will not open a browser by default.

I am not using this parameter, so no browser gets opened by default.

The problem appears to be that there's a check for `cls.waiters` in `LiveReloadHandler.poll_tasks` and `cls.waiters` is empty by default (when no browser has connected yet), correct?

So this code in `LiveReloadHandler.poll_tasks` will return, and not execute any tasks:

> if not filepath or delay == 'forever' or not cls.waiters

Apart from that: when using the INotifyWatcher, is it necessary to poll regularly after all?

**Comment by lepture** [comment]
@blueyed 

```python
    @classmethod
    def poll_tasks(cls):
        filepath, delay = cls.watcher.examine()
        if not filepath or delay == 'forever' or not cls.waiters:
            return

```

This `cls.watcher.examine()` will execute the task.

**Comment by blueyed** [comment]
You are right - it works now.
I must have messed something up / got confused between touching `css` and `scss` files (only the latter have a task).
