### ISSUE TITLE
No support for static files during development in Django

### ISSUE THREAD

**Issue by burhan** [lepture/python-livereload#120]
If you pass the Server instance the django WSGI application; it does not automatically handle static files, which is a big issue during development.

**Comment by RonnyPfannschmidt** [comment]
django wsgi by design does not handle static files, this is not livereload's fault

**Comment by burhan** [comment]
But it does make it difficult to use it during development, in fact if I run it separately with `livereload /path/to/my/proj/templates/` the server starts, but the browser doesn't refresh.

I one possible way to make it work could be by subclassing `Server` and passing it the static file handler (from django) along with the pattern.

I'll tinker around and see if I can come up with something.

**Comment by RonnyPfannschmidt** [comment]
bascially you need a more special wsgi app, also keep in mind that livereload is not aware of how django templates map to urls

**Comment by lepture** [comment]
`livereload` know nothing about Django, it only talks to wsgi.

@burhan you may subclass `Server` and rewrite `get_web_handlers` function. You can add a StaticHandler yourself.

https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L250

**Comment by burhan** [comment]
That's exactly what I was going to do. @lepture

**Comment by tjwalch** [comment]
If you want to try an alternative, I took some good parts from this project and combined them with other good things I found into a tool made for Django called [django-livereload-server](https://pypi.python.org/pypi?:action=display&name=django-livereload-server). It uses information from your Django settings file (e g staticfile finders) to find the templates and static files to watch.

**Comment by gilmrjc** [comment]
To solve this just serve the static files using [urls.staticfiles_urlpatterns](https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#django.contrib.staticfiles.urls.staticfiles_urlpatterns)

`from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# ... the rest of your URLconf here ...

urlpatterns += staticfiles_urlpatterns()`

Mayber this can be added to the Readme to avoid confusion.

**Comment by lepture** [comment]
@gilmrjc great. Could you add it in the docs and make a PR?
