### ISSUE TITLE
Optional -w WAIT parameter does not exist

### ISSUE THREAD

**Issue by kelvin22** [lepture/python-livereload#123]
The documentation names a '-w WAIT' optional parameter, does this still exist?

>$ livereload --help
>usage: livereload [-h] [-p PORT] [-w WAIT] [directory]
>
>Start a `livereload` server
>
>positional arguments:
>  directory             Directory to watch for changes
>
>optional arguments:
>  -h, --help            show this help message and exit
>  -p PORT, --port PORT  Port to run `livereload` server on
>  -w WAIT, --wait WAIT  Time delay before reloading

Running with this parameter does not work:
>livereload -w 530
>usage: livereload [-h] [--host HOST] [-p PORT] [directory]
>livereload: error: unrecognized arguments: -w

**Comment by lepture** [comment]
The documentation is a development version. If you install the code in master branch, you will get the `watch` parameter.

**Comment by kelvin22** [comment]
Thanks @lepture I never would have realised this, running the master code now :)
