### ISSUE TITLE
Assign watch for subdirectory does not restart the server one changes in that subdirectory

### ISSUE THREAD

**Issue by narath** [lepture/python-livereload#128]
Have a simple flask app with a templates subdirectory. I use the following for my livereload file

```python
from livereload import Server
from fhir_amp_tutorial import app

server = Server(app.wsgi_app)
server.watch('templates/', delay=2)
server.serve()
```

However when I change one of the template files, the server is not restarted. When I add in an alert, the alert gets triggered.

**Comment by lepture** [comment]
Yes. Watch will not restart the server itself. It will reload the page.
