### ISSUE TITLE
Script specifies host and port which breaks reverse proxies

### ISSUE THREAD

**Issue by xentac** [lepture/python-livereload#132]
https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L224

If I use a reverse proxy with livereload, it uses the server's port, not the exposed port.  Why not just use "/livereload.js"?  This would at least make reverse proxies work, though it still wouldn't let you put the site behind a specific path.

**Comment by corani** [comment]
:+1:

**Comment by lepture** [comment]
livereload.js is served on liveport, which can be different from your site port.

**Comment by corani** [comment]
`liveport` doesn't solve the issue when running behind a reverse proxy. If livereload.js runs on port 5000, behind a reverse proxy that forwards incoming port 80 to port 5000, the injected JavaScript that loads livereload.js uses the incorrect port (5000).

There is a difference between the port on which livereload.js is running, and the port clients should connect to. As a matter of fact (as @xentac) already indicated, it's not just the port, the path may be different as well.

**Comment by hoatle** [comment]
I've created a PR to fix this issue: https://github.com/lepture/python-livereload/pull/158 hopefully it should be merged soon.

**Comment by bmcculley** [comment]
Closing this, new release on pypi addresses this issue.
