### ISSUE TITLE
Fallback Content-Type should be application/octet-stream

### ISSUE THREAD

**Issue by waylan** [lepture/python-livereload#135]
In [Tornado][1], the fallback Content-Type is `application/octet-stream` for any unknown types. While LiveReload does not alter that behavior in its [`StaticFileHandler` subclass][2], it does use `text/html` [elsewhere][3]. When using LiveReload, the following file types are being returned with `Content-Type:text/html`:

File Extension | Expected Content-Type | Acceptable Fallback        | Actual
-------------- | --------------------- | -------------------------- | -----------
`.woff2`       | `font/woff2`          | `application/octet-stream` | `text/html`
`.woff`        | `font/woff`           | `application/octet-stream` | `text/html`
`.ttf`         | `font/ttf`            | `application/octet-stream` | `text/html`
`.mustache`    | `text/template`       | `application/octet-stream` | `text/html`
`.json`        | `application/json`    | `application/octet-stream` | `text/html`

I've included the expected content types above, but in all cases, modern browsers seem to behave as expected with `Content-Type:application/octet-stream` (see mkdocs/mkdocs#897). Therefore, it seems to me the fallback should be `application/octet-stream`.

I expected that LiveReload would just use whatever Tornado returned, and in fact with a a look at the code I can see `Content-Type:text/html` is only being set if no content type is already defined. But apparently something is awry.

[1]: https://github.com/tornadoweb/tornado/blob/master/tornado/web.py#L2589
[2]: https://github.com/lepture/python-livereload/blob/master/livereload/handlers.py#L150
[3]: https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L132

**Comment by lepture** [comment]
@waylan A PR is welcome.

**Comment by waylan** [comment]
This problem only appears to exist on Windows, which makes it hard to debug as all my tools are not on Windows.

**Comment by lepture** [comment]
@waylan me either. I don't have a PC.

**Comment by waylan** [comment]
The PR is at #136. For some reason it didn't get linked to this issue.

Any idea if/when this will be applied and/or released?
