### ISSUE TITLE
PyCharm error: Unknown command: 'livereload'

### ISSUE THREAD

**Issue by Ballpin** [lepture/python-livereload#139]
Hi,
I installed the package through settings->Project Interpreter> + > livereload. When i run it afterwards i receive the following error " Unknown command: 'livereload' ".  

settings.py:
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djangobower',
    'livereload',
]

Is it a bug or am i doing something wrong?

**Comment by sirex** [comment]
It looks that Django support was not yet released. Try this:

    pip install --upgrade 'git+https://github.com/lepture/python-livereload.git#egg=livereload'

**Comment by Ballpin** [comment]
Thanks, for the answer.

I will give it a shot as soon i start to edit backend more. Right now i decided to use webpack-dev-server for live development on frontend. :)
