### ISSUE TITLE
Integrating livereload with flask

### ISSUE THREAD

**Issue by arindampradhan** [lepture/python-livereload#144]
Hi I have written a script to livereload my pages...

```
from flask import Flask, send_from_directory ,render_template
from livereload import Server

app = Flask(__name__, static_url_path='/', static_folder='Views')


@app.route('/bower_components/<path:path>')
def send_assets(path):
    return send_from_directory('bower_components', path)


@app.route('/')
def index():
    return app.send_static_file('index.html')

@app.route('/logout')
def logout():
    return app.send_static_file('logout.html')

@app.route('/use_jinja')
def use_jinja():
    return render_template('useJiinja.html')


if __name__ == '__main__':
    server = Server(app.wsgi_app)
    server.serve()
    server.watch('/Views/*')
    app.run(debug=True)
```

Everything works fine for the root url **`/`**:
- but for _other urls_ the browser does not reload **`/logout`**
- and for template engine **jinja** it does not render or  not even show change **`/use_jinja`**

Can some one let me know how to write an adapter for livereload with a template language 
Or how do I log livereload , It would be really helpful..

**Comment by lepture** [comment]
you should use livereload server to run your app.

https://livereload.readthedocs.io/en/latest/

```python
server = Server(app.wsgi_app)
server.watch('/Views/*')
server.serve()
```

**Comment by lepture** [comment]
no `app.run()`.

**Comment by arindampradhan** [comment]
After trying that I get live reload on the page for only the ``root url`` **/**.
And when I use the render_template it still does not work .... :P 
Is it some os related issue. I was testing this on windows.... ??
Thanks for the help I will try figuring it out

**Comment by alexa-infra** [comment]
Since flask 0.11 templates are not automatically reloaded outside of debug mode. You can enable debug mode on your flask application ```app.config['DEBUG'] = True``` or enable template auto reload directly ```app.config['TEMPLATES_AUTO_RELOAD'] = True``` to make livereload work with ```render_template```.

**Comment by lepture** [comment]
documented on readme https://github.com/lepture/python-livereload/commit/ff0d74fabd49a9618d3cdfada6e2934973efdd98
