### ISSUE TITLE
error "Tried to write more data than Content-Length"

### ISSUE THREAD

**Issue by mshahbazi** [lepture/python-livereload#146]
Thank you for your great module.
I am trying to use livereload in falcon, but get the above error.
seems the content-length exceeds when livereload tries to inject the js file into html.
surfing your code, I figured out that you are adding the js length (<script> ...) to the content-length in `LiveScriptInjector` class. however, I could'n find where the class and corresponding function `transform_first_chunk` is called. here is my main.py:
```
app = falcon.API()
route.setup_routes(app)

server = livereload.Server(app)
server.serve(host=config.SERVER_HOST, port=config.SERVER_PORT, debug=True)
```
any help would be greatly appreciated

**Comment by mshahbazi** [comment]
found the solution. I made the following change and it worked!
```
server.LiveScriptContainer.__call__():
  ...
  for key, value in headers:
    if key.lower() == 'content-length':
        value = str(len(body))
    header_obj.add(key, value)
  ...
```
changed `key == 'Content-Length'` to `key.lower() == 'content-length'`
in falcon, headers are lowercase, thus Content-Length could not be detected and lengthened

you may commit this to the next release.
look forward to have your version
thanks again for the great work

**Comment by lepture** [comment]
@mshahbazi you can create a PR for it.

**Comment by mshahbazi** [comment]
done. thank you
