### ISSUE TITLE
Reload server from another thread

### ISSUE THREAD

**Issue by Peque** [lepture/python-livereload#149]
Hi,

What would be the best way to explicitly reload the server from another thread? I already have a thread that triggers on some events (like a watcher) and I would like it to force reload on the running server. Is that possible? How?

For now, I am writing from that thread on a file and then I add a watcher to the server to watch that file as well, but that seems "dirty" to me and was wondering if there was another way to do it.

Thanks for your help. :blush:

**Comment by Peque** [comment]
Also, even though I use this intermediate file, I cannot seem to make it reload instantly on each trigger. If two triggers occur too close together I get something like:

    [I 170216 18:53:02 handlers:80] Ignore: <path_to_intermediate_file>

Like if it is skipping some changes if they occur in a short period.

**Comment by bhrutledge** [comment]
After digging through the source investigating #197, I discovered that you can trigger a reload of `livereload.Server` via a `GET` to `http://{host}:{port}/forcereload`. Maybe you could do that in your your thread?

https://github.com/lepture/python-livereload/blob/f80cb3ae0f8f2cdf38203a712fe25ef7f1899c34/livereload/server.py#L220

https://github.com/lepture/python-livereload/blob/f80cb3ae0f8f2cdf38203a712fe25ef7f1899c34/livereload/handlers.py#L223-L227

**Comment by Peque** [comment]
Yeah, that works just fine. :+1:
