### ISSUE TITLE
Cannot import name 'Server'

### ISSUE THREAD

**Issue by gusg21** [lepture/python-livereload#150]
I have copied the code exactly as it was in the Documentation:

    #!/usr/bin/env python
    from livereload import Server, shell
    server = Server()
    server.watch('docs/*.rst', shell('make html', cwd='docs'))
    server.serve(root='docs/_build/html')

But I'm getting the error:

    -- snip --
        from livereload import Server
    ImportError: cannot import name 'Server'

At first I assumed that server might just be lowercase, so I tried that, but still nothing. Please help!

**Comment by lepture** [comment]
make sure you are using the latest release.

**Comment by gusg21** [comment]
"pip list" says version 2.5.1.

**Comment by lepture** [comment]
I have no idea. Maybe there is another `livereload` module in your PYTHONPATH.

**Comment by vpgrishkin** [comment]
Rename the example from livereload.py to other.

**Comment by i-give-up** [comment]
> Rename the example from livereload.py to other.

That's what fixed it for me.
