### ISSUE TITLE
[setup.py] Please add missing install_require dependency on pkg_resources

### ISSUE THREAD

**Issue by P-EB** [lepture/python-livereload#168]
Hi,

We realized in Debian that your python module's `setup.py` doesn't state that pkg_resources is required at installation by livereload while it's used in `handlers.py`.

Could you add it as a dependency in the `setup.py` file, please? :)

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896399 or https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896315 for more intel.

**Comment by RonnyPfannschmidt** [comment]
it should be noted that the "pkg_resources" package is only existing on debian as a rotten bad hack to split it out of setuptools and the correct python level dependency is setuptools

**Comment by RonnyPfannschmidt** [comment]
i propose using `pkgutil.get_data` as it seems sufficient for the use-case

**Comment by lepture** [comment]
@RonnyPfannschmidt I changed to file open and read.

**Comment by lepture** [comment]
2.5.2 released
