### ISSUE TITLE
Could you embed the images for download and pypi into README.rst?

### ISSUE THREAD

**Issue by P-EB** [lepture/python-livereload#169]
Hi,

In Debian, we are packaging your work in the source package python-livereload. The thing is, we have to maintain a patch that strips from the documentation the two images that are shipped by `README.rst` file, as hotlinking to external sites is a potential privacy breach for our users.

Could you embed into your project both of these images so that both images are shipped in the compiled documentation into Debian, and thus we don't break any privacy by having them and thus can drop our debian-specific patch?

Cheers!

**Comment by lepture** [comment]
You can send a PR to remove these badges.
