### ISSUE TITLE
Doesn't detect file deletion on macOS/Windows

### ISSUE THREAD

**Issue by bhrutledge** [lepture/python-livereload#197]
I was hoping to use this as a replacement for Pelican's development server, which has an option to automatically regenerate content when a file is created, updated, or deleted, but doesn't refresh the browser. I followed an [existing example](https://merlijn.vandeen.nl/2015/pelican-livereload.html) to get it going, but was surprised that files deleted from a watched directory/glob don't trigger a reload.

Looking through [watcher.py](https://github.com/lepture/python-livereload/blob/master/livereload/watcher.py), it looks like this might work on Linux via `INotifyWatcher` and `pyinotify`. However, it seems like the base `Watcher` class used macOS/Windows walks the glob/directory tree looking for changes to files based on modification time, with no check for files that no longer exist.

**Comment by justinmayer** [comment]
Perhaps consider outsourcing the change detection to a library dedicated to that purpose? Something like [Watchdog](https://github.com/gorakhargosh/watchdog)? Just an idea. 😊

**Comment by bhrutledge** [comment]
I was wondering about something like that. It looks like that would mean writing a subclass of  [`Watcher`](https://github.com/lepture/python-livereload/blob/master/livereload/watcher.py), e.g. `WatchdogWatcher`, similar to `INotifyWatcher`. The [`Server`](https://github.com/lepture/python-livereload/blob/master/livereload/server.py) class takes an optional `Watcher` instance, so I might start by implementing that for my custom `livereload` script, before trying to add it to this project.

**Comment by bhrutledge** [comment]
PR #198 takes a simpler approach, by augmenting the existing `Watcher`.
