### ISSUE TITLE
Exception raised when dynamically changing watchers

### ISSUE THREAD

**Issue by geographika** [lepture/python-livereload#202]
Thanks for a great project. 
I'm currently am writing a script that has a chain of changes, where a modification in one file mean new files should be watched. In skeleton code something like the following:

```python
def new_watchers():
    # read mylist from file1.txt
    for x in mylist:
        server.watch(x, shell(cmd), delay=2)

server.watch("file1.txt", new_watchers)
server.serve(liveport=35729)
```

This actually all runs perfectly with the new file served/watched for changes. The log however has a raised exception:

```
[E 190609 23:34:56 ioloop:909] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "\lib\site-packages\tornado\ioloop.py", line 907, in _run
        return self.callback()
      File "\lib\site-packages\livereload\handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "\lib\site-packages\livereload\watcher.py", line 91, in examine
        for path in self._tasks:
    RuntimeError: dictionary changed size during iteration
```

**Comment by pradyunsg** [comment]
I'm pretty sure this is not going to be possible given the current implementation approach used in this project. I don't think this is a common enough usecase to justify the additional complexity *right now* so I'm gonna close this right now to indicate that it's not going to a supported way to use this project.

We can revisit this at a later date, but unless someone other than OP also expresses interest in this sort of behavior, I don't think it'll be likely that this gets implemented. :)
