### ISSUE TITLE
Debouncing changes which happen in succession

### ISSUE THREAD

**Issue by jtmoulia** [lepture/python-livereload#205]
I find that if I have livereload monitoring many files and I change all of those files I will get a rebuild for each change. Instead, I want one rebuild at the end of the quick succession of changes.

This issue often happens when switching source branches.

Is there a way to do this in `livereload`? If not, I might be able to create a PR.

Thanks!

**Comment by pradyunsg** [comment]
I'm unable to reproduce this behavior now (MacOS Catalina, latest version of livereload).
