### ISSUE TITLE
Usage with Flask Socket IO

### ISSUE THREAD

**Issue by clitetailor** [lepture/python-livereload#206]
Is there any example on how to start `python-livereload` with `flask` and `flask-socketio`?

**Comment by david-ml** [comment]
Hey there,
I was able to get `livereload` and `flask-socket-io` working together by calling `Server()` on `app.wsgi_app` instead of on `app` itself, as seen below:

```
if __name__ == '__main__':
    server = Server(app.wsgi_app)
    server.serve()
    socketio.run(app, log_output=False)
```

**Comment by JunkyByte** [comment]
This does not work, `server.serve()` blocks the execution and prevents the `socketio.run` am I missing something obvious? Anybody has a working solution? Thank you
