### ISSUE TITLE
Shell: Run command in Python environment

### ISSUE THREAD

**Issue by fleimgruber** [lepture/python-livereload#212]
A docs build chain using python scripts instead of "make html" would need to run in a specific virtualenv or conda environment. What are your ideas on supporting this?

**Comment by pradyunsg** [comment]
It's fairly straightforward to do this without specific support in this tool:

```
/python/to/environment/bin/python script.py
```

On Windows, it'll be:

```
drive:\python\to\environment\Scripts\python script.py
```

---

I don't think this needs specific support in livereload.

**Comment by fleimgruber** [comment]
Thanks for checking back. Indeed I tried to use it the way you said back when I created the issue. Either some `shell` related code changed in the meantime or I had the wrong env setup. In any case, just tried it now as I did back then with the custom python scripts and that works.
