### ISSUE TITLE
Python3.8 support?

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [lepture/python-livereload#215]
It does not currently support 3.8. When will 3.8 support be enabled? thanks!

**Comment by bmcculley** [comment]
Hi @Abdur-rahmaanJ can you share more details please? I know `os.errno` and syncio on windows, is there anything else that you know of? Thank you.

**Comment by Abdur-rahmaanJ** [comment]
@bmcculley i just know that when i tried running with 3.8 it did not run. Maybe beacause of install instructions or i don't remember. I had to use 3.7

**Comment by bmcculley** [comment]
@Abdur-rahmaanJ thank you for getting back so quickly. One more question, were you running on a Windows machine?

**Comment by Abdur-rahmaanJ** [comment]
Yes windows

**Comment by bmcculley** [comment]
Thank you! Just merged a fix for this into master.

**Comment by bmcculley** [comment]
Closing this, just created a new release on pypi.
