### ISSUE TITLE
Prevents selecting in editor

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [lepture/python-livereload#223]
Running livereload with flask prevents selection of text in sublimetext on windows 

python 3.8 - livereload 2.6.2

**Comment by pradyunsg** [comment]
I'm unable to reproduce this, and it might be related to a Sublime Text extension instead of this project.

**Comment by Abdur-rahmaanJ** [comment]
Hum ok, if i can pin it down, i'll drop a comment here!
