### ISSUE TITLE
Want another maintainer? Add me. :)

### ISSUE THREAD

**Issue by pradyunsg** [lepture/python-livereload#230]
Ahoy @lepture! I see an all-caps "MAINTAINERS NEEDED" on this repository.

I'd be happy to take over maintainership of this project. Would you be willing to add me as an admin/transfer this project over to me so that I could take it forward? Notably, I'm interested in this project coming from sphinx-autobuild (a downstream user of this package) and plan to put this project under jazzband in the long run.

**Comment by pradyunsg** [comment]
*nudge*

**Comment by lepture** [comment]
ping @bmcculley

**Comment by lepture** [comment]
@pradyunsg thanks. I've invited you.

**Comment by pradyunsg** [comment]
Wheee! Thanks @lepture! ^>^

**Comment by pradyunsg** [comment]
Ahoy @lepture, could you add me as an owner of the project on PyPI?

**Comment by lepture** [comment]
@pradyunsg what’s your pypi username?

**Comment by pradyunsg** [comment]
pradyunsg :)

**Comment by pradyunsg** [comment]
_nudge_

**Comment by lepture** [comment]
@pradyunsg I've already invited you. But the invite is expired. I'm inviting you again. Please check your email.

**Comment by pradyunsg** [comment]
Donezo!

**Comment by pradyunsg** [comment]
@lepture Could you add me to Read the Docs as well? https://readthedocs.org/projects/livereload/

**Comment by lepture** [comment]
@pradyunsg added.
