### ISSUE TITLE
Rename livereload to live_reload

### ISSUE THREAD

**Issue by SmartManoj** [lepture/python-livereload#237]
collides with liver

liver/eload 
liverel/oad

**Comment by antoshammah-econote** [comment]
ipdi name change pana wrk agutha bro?

**Comment by SmartManoj** [comment]
It's just for reading convention.

**Comment by pradyunsg** [comment]
Thanks for filing this!

This naming scheme matches the underlying package's name (livereload.js) and changing the project's PyPI name would be a disruptive change. Since eload and /oad are not a valid English words, I expect that most readers will read this as live/reload.

**Comment by antoshammah-econote** [comment]
$ python3 manage.py runserver 0:8000 after passing this command 
______________________________________________________________________________
im getting error
"  File "/home/ubuntu/django-withsql/env/lib/python3.8/site-packages/django/template/backends/django.py", line 123, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'livereload.templatetags.livereload_tags': cannot import name 'livereload_host' from 'livereload' (unknown location) "
______________________________________________________________________________________
note : need  requirements have been installed 
still im getting this
