### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [lepture/python-livereload#240]
Wheels (`.whl`) for this package are [currently missing from PyPI](https://pypi.org/project/livereload/2.6.3/#files). Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by johnthagen** [comment]
It looks as though wheels used to be uploaded as recent as: https://pypi.org/project/livereload/2.6.1/#files

Did something change in the release procedures such that wheels are no longer being published?

**Comment by McSinyx** [comment]
I am curious as well.

**Comment by pradyunsg** [comment]
I'd be happy to do this, should @lepture provide me with the ability to uplaod on PyPI.

**Comment by hugovk** [comment]
@pradyunsg I see you're now listed as a maintainer on [PyPI](https://pypi.org/project/livereload/)! 🚀

**Comment by stevepiercy** [comment]
Adding a wheel might silence the current deprecation notice.

> DEPRECATION: livereload is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Comment by pradyunsg** [comment]
Uploaded a wheel for 2.6.3.

That deprecation is related to the fact that you don't have the `wheel` package installed in the virtual environment you're building/installing this package in; and is more related to the fact that pip is gonna change its behaviour soon. :)

**Comment by stevepiercy** [comment]
Thanks. We'll add `wheel` to our requirements.

**Comment by brianpeiris** [comment]
FYI, this new WHL package broke our CI build because pip will use the new WHL package before it uses the old tar.gz package. Our build then failed because the SHA of the new package does not match the SHA in the requirements.txt generated by pip-compile.

It may not be best to try to undo this now (we've already updated to the new SHA), but please be careful when uploading new packages for old versions.
