### ISSUE TITLE
Log to 'livereload' logger name instead of root logger

### ISSUE THREAD

**Issue by t0m** [lepture/python-livereload#85]
Hi, instead of logging to the rootLogger via 

    import logging
    logging.info('stuff')

I think it would be better to use a named logger via:

    import logging
    logger = logging.getLogger(__name__)
    logger.info('stuff')

This way gives the user more granular control and won't accidentally interfere with the user's settings if they had already set up their root logger.  I'd be happy to provide a PR if you agree.

**Comment by lepture** [comment]
@t0m I'd like to

**Comment by tterrace** [comment]
Hey @lepture , was your response cut off?

**Comment by t0m** [comment]
Ooops, accidentally commented under my work account, tterrace is me

**Comment by blueyed** [comment]
@t0m 
It probably means that a PR for this would be accepted.. :)

**Comment by sloria** [comment]
+1. We ran into this when our app's logs being silenced in debug mode.

Will submit a patch soon.
