### ISSUE TITLE
Document how to use livereload

### ISSUE THREAD

**Issue by mgedmin** [lepture/python-livereload#94]
Hello!

I came here from http://serialized.net/2013/01/live-sphinx-documentation-preview/ and got all confused: the blog post talks about Guardfiles, which is not mentioned once in http://livereload.readthedocs.org/en/latest/ or in the repository.

Trawling through the issues makes me think python-livereload used a Guardfile at some point, and then stopped.  Instead I now have to write a Python script with the right incantations.  Fair enough, but it'd be nice if the documentation had a small note about this, with an example describing how to convert a Guardfile like the one mentioned in the above blog post into a script.

**Comment by lepture** [comment]
@mgedmin Yes. It was redesigned. There are many tools to do livereload, python-livereload had no difference. I redesigned it to be special for Python so that it can power WSGI application.

It is redesigned for developers, not for ordinary users. That's why you should write Python scripts instead of Guardfile now.

I am sorry for the inconvenience. Here is a little hint on the documentation http://livereload.readthedocs.org/en/latest/#developer-guide you don't have to pass the wsgi_app.

**Comment by mgedmin** [comment]
I've figured it out, for my Sphinx documents:

```python
from livereload import Server, shell

server = Server()
server.watch('*.rst', shell('make html'))
server.watch('*/*.rst', shell('make html'))  # there's no support for arbitrary-depth recursive globbing :(
server.serve(root='_build/html', open_url=True)
```

I couldn't find any documentation for the `root` and `open_url` arguments to `serve()`.  I had to read the source code to discover them.  I'll try to submit a documentation PR to fix that.

**Comment by lepture** [comment]
@mgedmin That would be terrific.

**Comment by mgedmin** [comment]
Actually, I'm confused now: the Sphinx doc uses autodoc for the Server class, but the docs at http://livereload.readthedocs.org/en/latest/#server-watch do not resemble the docstrings in [the source tree](https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L107).

Perhaps this is already fixed in master, just not released yet?

I'm unable to verify locally since 'make docs' fails with "no theme named 'flask_small' found (missing theme.conf?)", and I've no idea how to install it.

**Comment by lepture** [comment]
@mgedmin I've just included the inherited members: http://livereload.readthedocs.org/en/latest/#livereload.Server.serve


Install the theme with:

```
$ git submodule init
$ git submodule update
```
