### ISSUE TITLE
Ignore open_url=True when live-reloading the server

### ISSUE THREAD

**Issue by mgedmin** [lepture/python-livereload#95]
I've a `live.py` that looks like this:

```python
from livereload import Server

server = Server()
# no recursive globbing on Python 2 :(
for pattern in '*.rst', '*/*.rst':
    server.watch(pattern, 'make html')
server.serve(root='_build/html', open_url=True)
```

Every time I make a change to it, I see

>  [I 150408 13:13:54 autoreload:195] live.py modified; restarting server

on the console, and then I get a new browser tab.

I *like* that livereload reloads its own configuration every time the script changes, but would it be possible to ignore open_url when the reload happens?

**Comment by lepture** [comment]
@mgedmin Currently no. Just turn off the `open_url`. Maybe I will fix it in the future.
