### ISSUE TITLE
Wishlist: recursive watching for a file pattern

### ISSUE THREAD

**Issue by mgedmin** [lepture/python-livereload#97]
I want to run a command whenever a filename matching a particular glob pattern (`*.rst`) changes in a directory tree.

I can watch the directory tree recursively with `server.watch('directory/')`, but this triggers for other kinds of files as well.

I can watch for a glob pattern (`*.rst`), but this doesn't support recursive globbing ([yet](https://docs.python.org/dev/whatsnew/3.5.html#glob)).

Possible solutions:
- implement `'**/*.rst'`-style globbing (perhaps backport the feature from Python 3.5?)
- add a `filter` argument so I could say `server.watch('.', filter=lambda fn: fn.endswith('.rst'), func='make html')`

Note that a solution to manually use an external library for file globbing, like the one [suggested in the manual](http://livereload.readthedocs.org/en/latest/#server-watch), is unsuitable because it would not pick up newly-created files or subdirectories.

**Comment by mgedmin** [comment]
BTW a `filter` callable would also allow you to define arbitrary files to ignore, which was requested in #28:
```
server.watch('.', filter=lambda fn: not fn.endswith('.log'), ...)
```
You could also add an `ignore()` helper like the `shell()` one, that would return a callable to filter out undesirable files:
```
server.watch('.', filter=ignore('*.log', 'test*', ...), ...)
```

**Comment by camilonova** [comment]
Agree, this is needed when you need to deal with a large project.

**Comment by camilonova** [comment]
Currently in gulp we are using:

```
    // When a django template is changed reload
    gulp.watch('**/templates/**/*').on('change', livereload.changed);
```

**Comment by lepture** [comment]
I've added an `ignore` parameter on watch https://github.com/lepture/python-livereload/commit/26c70a709b6b74dae02c6a4548b393255c08cf59

**Comment by mgedmin** [comment]
`Server().watch()` doesn't take an `ignore` argument in 2.4.0:
```
Traceback (most recent call last):
  File "live.py", line 18, in <module>
    server.watch('.', shell('make html'), ignore=ignore)
TypeError: watch() got an unexpected keyword argument 'ignore'
```

**Comment by mgedmin** [comment]
See https://github.com/lepture/python-livereload/pull/127
